##############################
# Netlify configuration file #
##############################

# List of Build plugins
[[plugins]]
# since this isn't on the netlify plugin list yet, going 
# to hopefully shortcircuit by feeding it a package.json 
package = "@quarto/netlify-plugin-quarto"
  # Plugin configuration
  #  [plugins.inputs]
  #  foo = "bar"

[build]
# Dummy build command
command = "echo 'done'"

